FROM python:3.9-slim

RUN apt-get update

RUN pip install --upgrade pip
RUN pip install kafka-python

WORKDIR /python-docker

RUN mkdir results

COPY ./read/read_from_kafka.py .

CMD [ "python3", "read_from_kafka.py"]