###
# Task 1
POST http://localhost:8080/
Content-Type: application/json

{
  "question": 1,
  "uid": "C351297720"
}

###
# Task 2
POST http://localhost:8080/
Content-Type: application/json

{
  "question": 2,
  "uid": "C1259780697"
}

###
# Task 3
POST http://localhost:8080/
Content-Type: application/json

{
  "question": 3,
  "uid": "C308411778",
  "start_date": "2022-05-01",
  "end_date": "2022-05-15"
}
