USE hw2_omelkina;

INSERT INTO favorite_songs (id, author, song_name, release_year) VALUES (0, 'Queen', 'Bicycle Race', 1978);
INSERT INTO favorite_songs (id, author, song_name, release_year) VALUES (1, 'Ozzy Osbourne', 'Mama, I am coming home', 1991);

INSERT INTO favorite_movies (id, name, producer, release_year) VALUES (0, 'Spirited Away', 'Toshio Suzuki', 2001);
INSERT INTO favorite_movies (id, name, producer, release_year) VALUES (1, 'Whisper of the Heart', 'Toshio Suzuki', 1995);

